############################################################################
#
# This file is part of BuildADoc.
#
# (c) Guido Obst
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#
############################################################################

FROM ghcr.io/gobst/buildadoc/buildadoc:1.0.0

LABEL maintainer="Guido Obst" \
	  description="BuildADoc develop image" \
	  version="1.0.0"

WORKDIR /var/www/html/BuildADoc

ARG php_version=8.3
ARG buildadoc_path=/var/www/html/BuildADoc
ARG phpCompatibilityPath=/var/www/html/BuildADoc/tools/php-compatibility
ARG phpCsFixerPath=/var/www/html/BuildADoc/tools/php-cs-fixer
ARG phpCodesnifferPath=/var/www/html/BuildADoc/tools/php_codesniffer
ARG PhpmdPath=/var/www/html/BuildADoc/tools/phpmd
ARG psalmPath=/var/www/html/BuildADoc/tools/psalm

# install xdebug
RUN aptitude update
RUN aptitude install -y php8.3-xdebug

# run composer
RUN composer install

# create folder
RUN mkdir ${buildadoc_path}/tests \
    ${buildadoc_path}/scripts \
    ${buildadoc_path}/tools \
    ${buildadoc_path}/tools/php-compatibility \
    ${buildadoc_path}/tools/php-cs-fixer \
    ${buildadoc_path}/tools/php_codesniffer \
    ${buildadoc_path}/tools/phpmd \
    ${buildadoc_path}/tools/psalm \
    ${buildadoc_path}/bin/output

RUN chmod 755 ${buildadoc_path}/bin/output

# copy files
COPY tests ${buildadoc_path}/tests
COPY cfg/dev ${buildadoc_path}/cfg/dev
COPY scripts ${buildadoc_path}/scripts
COPY res/docker/config/xdebug/xdebug.ini /etc/php/${php_version}/mods-available/xdebug.ini
COPY res/docker/config/xdebug/xdebug.ini /etc/php/${php_version}/cli/conf.d/20-xdebug.ini

## tools
COPY tools/php-compatibility/composer.json ${phpCompatibilityPath}
COPY tools/php-compatibility/composer.lock ${phpCompatibilityPath}
COPY tools/php-cs-fixer/composer.json ${phpCsFixerPath}
COPY tools/php-cs-fixer/composer.lock ${phpCsFixerPath}
COPY tools/php_codesniffer/composer.json ${phpCodesnifferPath}
COPY tools/php_codesniffer/composer.lock ${phpCodesnifferPath}
COPY tools/phpmd/composer.json ${PhpmdPath}
COPY tools/phpmd/composer.lock ${PhpmdPath}
COPY tools/psalm/composer.json ${psalmPath}
COPY tools/psalm/composer.lock ${psalmPath}

COPY phpunit.xml ${buildadoc_path}
COPY infection.json5 ${buildadoc_path}
COPY rector.php ${buildadoc_path}

# run composer for tools
RUN composer install -d ${phpCompatibilityPath}
RUN composer install -d ${phpCsFixerPath}
RUN composer install -d ${phpCodesnifferPath}
RUN composer install -d ${PhpmdPath}
RUN composer install -d ${psalmPath}

RUN ls -l

EXPOSE 8081

CMD tail -f /dev/null