############################################################################
#
# This file is part of BuildADoc.
#
# (c) Guido Obst
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#
############################################################################

FROM ghcr.io/gobst/buildadoc/buildadoc:1.0.0

LABEL maintainer="Guido Obst" \
	  description="BuildADoc develop image" \
	  version="1.0.0"

WORKDIR /var/www/html/BuildADoc

ARG php_version=8.3
ARG buildadoc_path=/var/www/html/BuildADoc
ARG phpCompatibilityPath=tools/php-compatibility
ARG phpCsFixerPath=tools/php-cs-fixer
ARG phpCodesnifferPath=tools/php_codesniffer
ARG PhpmdPath=tools/phpmd
ARG psalmPath=tools/psalm

# install xdebug
RUN aptitude update
RUN aptitude install -y php8.3-xdebug

# create folder
RUN mkdir tests \
    scripts \
    tools \
    bin \
    bin/output

RUN chmod 755 bin/output

# copy directories and files
COPY tests tests
COPY cfg/dev cfg/dev
COPY scripts scripts
COPY tools tools
COPY res/docker/config/xdebug/xdebug.ini etc/php/${php_version}/mods-available/xdebug.ini
COPY res/docker/config/xdebug/xdebug.ini etc/php/${php_version}/cli/conf.d/20-xdebug.ini

COPY phpunit.xml .
COPY infection.json5 .
COPY rector.php .

# run composer
RUN composer install

# run composer for tools
RUN composer install -d ${phpCompatibilityPath}
RUN composer install -d ${phpCsFixerPath}
RUN composer install -d ${phpCodesnifferPath}
RUN composer install -d ${PhpmdPath}
RUN composer install -d ${psalmPath}

EXPOSE 8081

CMD tail -f /dev/null