############################################################################
#
# This file is part of BuildADoc.
#
# (c) Guido Obst
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#
############################################################################

services:
  buildadoc:
    build:
      context: ../../..
      dockerfile: res/docker/images/Dockerfile
    image: gobst/buildadoc/buildadoc:1.0.0
    container_name: buildadoc_container
  buildadoc-dev:
    build:
      context: ../../..
      dockerfile: res/docker/images/Dockerfile-dev
    image: gobst/buildadoc/buildadoc-dev:1.0.0
    container_name: buildadoc-dev_container