name: Update msi

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GitHub packages
        run: echo "${{ secrets.TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Pull image
        run: |
          docker compose -f res/docker/config/docker-compose.yml -p buildadoc-dev pull

      - name: Start container
        run: |
          docker compose -f res/docker/config/docker-compose.yml -p buildadoc-dev up -d

      - name: Run composer
        run: |
          docker compose -f res/docker/config/docker-compose.yml -p buildadoc-dev exec -T buildadoc-dev sh -c "composer install"

      - name: Run mutation tests
        run: |
          mkdir -p bin/output/mutation
          docker compose -f res/docker/config/docker-compose.yml -p buildadoc-dev exec -T buildadoc-dev sh -c "XDEBUG_MODE=coverage ./scripts/test/infectionPHP.sh"
          docker cp buildadoc-dev_container:/var/www/html/BuildADoc/bin/output/mutation/infection.json bin/output/mutation

      - name: Upload MSI to Stryker Dashboard
        run: |
          curl -X POST "https://dashboard.stryker-mutator.io/api/reports/github.com/gobst/buildadoc" \
          -H "Content-Type: application/json" \
          -d "@bin/output/mutation/infection.json"

      - name: Stop container
        if: always()
        run: |
          docker compose -f res/docker/config/docker-compose.yml -p buildadoc-dev down