name: Update coverage

on:
  workflow_dispatch:
  push:
    branches:
      - "develop"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install dependencies
        run: composer install --no-progress --no-suggest --prefer-dist

      - name: Run tests
        run: bin/phpunit --coverage-clover coverage.xml

      - name: Coveralls
        uses: coverallsapp/github-action@v1
        with:
          github-token: ${{ secrets.TOKEN }}
          path-to-lcov: coverage.xml
