name: Update coverage

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GitHub packages
        run: echo "${{ secrets.TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Pull image
        run: |
          docker compose -f res/docker/config/docker-compose.yml -p buildadoc-dev pull

      - name: Start container
        run: |
          docker compose -f res/docker/config/docker-compose.yml -p buildadoc-dev up -d

      - name: Run composer
        run: |
          docker compose -f res/docker/config/docker-compose.yml -p buildadoc-dev exec -T buildadoc-dev sh -c "composer install"

      - name: Run unit tests
        run: |
          mkdir -p bin/output
          docker compose -f res/docker/config/docker-compose.yml -p buildadoc-dev exec -T buildadoc-dev sh -c "XDEBUG_MODE=coverage ./scripts/test/phpunit.sh run"
          docker cp buildadoc-dev_container:/var/www/html/BuildADoc/bin/output/unit/coverage.xml bin/output

      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: bin/output/coverage.xml

      - name: Stop container
        if: always()
        run: |
          docker compose -f res/docker/config/docker-compose.yml -p buildadoc-dev down