name: Update badges

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build and publish docker images"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u ${{ secrets.DOCKER_HUB_USER }} --password-stdin

      - name: Pull image
        run: |
          docker compose -f res/docker/config/docker-compose.yml -p buildadoc-dev pull

      - name: Start container
        run: |
          docker compose -f res/docker/config/docker-compose.yml -p buildadoc-dev up -d

      - name: Run composer
        run: |
          docker compose -f res/docker/config/docker-compose.yml -p buildadoc-dev exec -T buildadoc-dev sh -c "composer install"

      - name: Run unit tests
        run: |
          mkdir -p bin/output
          docker compose -f res/docker/config/docker-compose.yml -p buildadoc-dev exec -T buildadoc-dev sh -c "XDEBUG_MODE=coverage ./scripts/test/phpunit.sh run"
          docker cp buildadoc-dev_container:/var/www/html/BuildADoc/bin/output/unit/coverage.xml bin/output

      - name: Upload coverage report to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: bin/output/coverage.xml

      - name: Run mutation tests
        run: |
          mkdir -p bin/output/mutation

          docker compose -f res/docker/config/docker-compose.yml -p buildadoc-dev exec -T buildadoc-dev sh -c "XDEBUG_MODE=coverage ./scripts/test/infectionPHP.sh"
          docker cp buildadoc-dev_container:/var/www/html/BuildADoc/bin/output/mutation/infection.json bin/output/mutation
          cd bin/output/mutation

          if [ ! -f "infection.json" ]; then
            echo "The infection.json file doesn't exist!"
            exit 1
          fi

          mutationScore=$(jq '.stats.msi' "infection.json")
          echo "{\"mutationScore\": $mutationScore}" > mutationScore.json

      - name: Upload MSI to Stryker Dashboard
        run: |
          cat bin/output/mutation/mutationScore.json

          curl -X PUT \
          "https://dashboard.stryker-mutator.io/api/reports/github.com/gobst/buildadoc/main" \
          -H 'Content-Type: application/json' \
          -H 'Host: dashboard.stryker-mutator.io' \
          -H "X-Api-Key: ${{ secrets.STRYKER_API_TOKEN }}" \
          -d "@bin/output/mutation/mutationScore.json"

      - name: Stop container
        if: always()
        run: |
          docker compose -f res/docker/config/docker-compose.yml -p buildadoc-dev down